### ISSUE TITLE
train_net.py

### ISSUE THREAD

**Issue by living1001** [swords123/IDA-3D#13]
我运行train。。。为什么总是出现这个问题ImportError: cannot import name '_C'，怎么解决的？

**Comment by swords123** [comment]
环境没配置好吧，你可以用我做好的那个singularity环境。还有就是要运行一下python setup.py build develop

**Comment by living1001** [comment]
链接打不开，可以发个别形式的吗？

**Comment by living1001** [comment]
我的torch1.9，cuda11.1

**Comment by swords123** [comment]
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md
照着这个链接配置不好用吗？
最好用 PyTorch 1.1.0, CUDA 10.0  高版本我也没试过，pytorch不同版本之间兼容性还是挺差的。
