### ISSUE TITLE
Compare with the Pseudo-LiDAR [25] of stereo version

### ISSUE THREAD

**Issue by Sukaiqi** [swords123/IDA-3D#15]
Your paper:
![image](https://user-images.githubusercontent.com/46585700/131512385-81c364c7-0875-417e-8d71-816c2e64bc7c.png)
 Pseudo-LiDAR paper:
![image](https://user-images.githubusercontent.com/46585700/131512495-a931ace1-7d8b-47f9-bc6d-831b8e6a4cc4.png)

I want to know the source of the pseudo-radar value in your paper. Thank you very much!

**Comment by swords123** [comment]
I use the result in [Pseudo-LiDAR](https://arxiv.org/pdf/1812.07179v2.pdf), which is the v2 version in arixiv, but it seems that the author modified the results in subsequent versions. You can find this results of Pseudo-Lidar in https://arxiv.org/pdf/1812.07179v2.pdf

**Comment by swords123** [comment]
![image](https://user-images.githubusercontent.com/18377091/132979014-ad06e20d-04f3-494b-8401-70c83af48227.png)
