### ISSUE TITLE
An error occurred when running "singularity shell --nv ubutu18-cuda10.simg"

### ISSUE THREAD

**Issue by KinkangLiu** [swords123/IDA-3D#17]
Hi，Thank you very much for your excellent work.  An error occurred when running "singularity shell --nv ubutu18-cuda10.simg"

~$ singularity shell --nv ubutu18-cuda10.simg
ERROR  : Image path doesn't exists
ABORT  : Retval = 255

Do you know what might be the reason？

**Comment by swords123** [comment]
Is the file "ubutu18-cuda10.simg" on the current forder? what is the path of "ubutu18-cuda10.simg"?

**Comment by KinkangLiu** [comment]
> Is the file "ubutu18-cuda10.simg" on the current forder? what is the path of "ubutu18-cuda10.simg"?

I put the  file "ubutu18-cuda10.simg" on '/IDA-3D-master'， and the error is changed

$  singularity shell --nv ubutu18-cuda10.simg
ERROR  : Unknown image format/type: ubutu18-cuda10.simg
ABORT  : Retval = 255

**Comment by swords123** [comment]
I don't know the reason for this problem, may be the version of the singularity. I use singulrity 3.0. and may be the image file broken when you download?
