### ISSUE TITLE
I wonder what each of the four values after "0-10:" means.

### ISSUE THREAD

**Issue by JangChangWon** [swords123/IDA-3D#18]
Thank you for releasing the code.
I have a question while studying your code, so I want to ask you.
The results of the interference are as follows:

maskrcnn_venchmakr. inference INFO: positions_z : 0.6279727, 0.7480121
0 - 10 : 0.28888804, 3.0077264          0.14014673, 19.665281
10 - 20: 0.xxxxxxx, 0.xxxxxxxxx            0.xxxxxxx, 0.xxxxxxxxx
~
~
~

I wonder what each of the four values after "0-10:" means

Thank you for reading

**Comment by swords123** [comment]
They refer to the mean and variance of the error of the estimated depth and disparity. Please refer to /maskrcnn_benchmark/data/datasets/evaluation/kitti/kitti_eval.py for more detail.
