### ISSUE TITLE
Directory error during evaluation

### ISSUE THREAD

**Issue by yhs-ai** [swords123/IDA-3D#19]
Hello, 
I am trying to use the pre-trained model for the evaluation.
./test.sh and python generate_results.py  were done without any error.
However, when I run the evaluation with ./kitti_eval/evaluate_object datasets/kitti/label_2 self_exp/exp_1/kitti_test/result_xxx command, it gives me an message like below:

mkdir: cannot create directory 'self_exp/exp_1/kitti_test/result_xxx/plot': No such file or directory
Loading detections...
number of files for evaluation: 0
  done.

It fails to make the directory and the number of files for evaluation comes out as 0.
How to solve the issue?

Thank you for your help.

**Comment by swords123** [comment]
For the directory "result_xxx", "xxx" is the iteration number you used, and you should change "xxx" to the iteration number of the model file.
