### ISSUE TITLE
How to get post-processed data?

### ISSUE THREAD

**Issue by milmario** [swords123/IDA-3D#20]
Hi,
I followed your [link](https://drive.google.com/file/d/1jir7_FOGbwTe_4fb-_6EsARsfQPv19Hh/view) to the post-processed data, but there are only 
- calib
- label_3d
- splits

where can i find the 

- image_2
- image_3
- label_2

in the right format?

**Comment by swords123** [comment]
You can download the [KITTI dataset](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) directly! 
and then, flipped the these  data as:
```python
    im_left_flip = cv2.flip(im_right,1)
    im_right_flip = cv2.flip(im_left, 1)

    cv2.imwrite(os.path.join(image_2_fliped_path, index + '.png'), im_left)
    cv2.imwrite(os.path.join(image_2_fliped_path, index + '_flip.png'), im_left_flip)

    cv2.imwrite(os.path.join(image_3_fliped_path, index + '.png'), im_right)
    cv2.imwrite(os.path.join(image_3_fliped_path, index + '_flip.png'), im_right_flip)
```
