### ISSUE TITLE
a issue about orientation regression

### ISSUE THREAD

**Issue by Hexuanfang** [swords123/IDA-3D#4]
hi, thanks for public your code work firslty. 
i got a confusion when i compare the code and the paper in the part of orientation regression. according to the paper, the orientation angle was calculated by the estimated viewpoint angle, that makes sense, but when i read the implemented code, it regresses the encoded orientation angle directly instead. so i was wondering did i misunderstand something? 
looking forward to your reply, thanks in advance.

**Comment by swords123** [comment]
In our preprocessed label file, "alpha" is the viewpoint angle and "beta" is the orientation angle, we use "alpha" as the target for the orientation regression, and transform "alpha" to "beta" to calculate the performance.
