### ISSUE TITLE
Code for 3D CNN

### ISSUE THREAD

**Issue by waychin-weiqin** [swords123/IDA-3D#6]
Hi, I cant find the part of your code where you construct the cost volume and the nonuniform quantization. Can you point me to where can I find them in your repo? 

Thank you very much

**Comment by swords123** [comment]
I'm very sorry that I didn't reply in time， you can find the implement of the cost volume and the nonuniform  quantization in [here](https://github.com/swords123/IDA-3D/blob/master/maskrcnn_benchmark/modeling/roi_heads/cost_volum_v11_head/depth_cost_feature_extractors.py)
